DOMAIN = "gardena_smart_system"
GARDENA_SYSTEM = "gardena_system"
GARDENA_LOCATION = "gardena_location"
GARDENA_CONFIG = "gardena_config"
CONF_MOWER_DURATION = "mower_duration"
CONF_SMART_IRRIGATION_DURATION = "smart_irrigation_control_duration"
CONF_SMART_WATERING_DURATION = "smart_watering_duration"

ATTR_NAME = "name"
ATTR_ACTIVITY = "activity"
ATTR_BATTERY_STATE = "battery_state"
ATTR_RF_LINK_LEVEL = "rf_link_level"
ATTR_RF_LINK_STATE = "rf_link_state"
ATTR_SERIAL = "serial"
ATTR_OPERATING_HOURS = "operating_hours"
ATTR_LAST_ERRORS = "last_error"
