"""Constants for the Gardena Smart System integration."""
from __future__ import annotations

from typing import Final

from homeassistant.components.lawn_mower import LawnMowerActivity

# Domain
DOMAIN: Final = "gardena_smart_system"

# Configuration keys
CONF_CLIENT_ID: Final = "client_id"
CONF_CLIENT_SECRET: Final = "client_secret"

# API constants
API_BASE_URL: Final = "https://api.smart.gardena.dev/v2"
API_TIMEOUT: Final = 30

# Device types
DEVICE_TYPE_MOWER: Final = "MOWER"
DEVICE_TYPE_VALVE: Final = "VALVE"
DEVICE_TYPE_POWER_SOCKET: Final = "POWER_SOCKET"
DEVICE_TYPE_SENSOR: Final = "SENSOR"

# Service types
SERVICE_TYPE_COMMON: Final = "COMMON"
SERVICE_TYPE_MOWER: Final = "MOWER"
SERVICE_TYPE_VALVE: Final = "VALVE"
SERVICE_TYPE_POWER_SOCKET: Final = "POWER_SOCKET"
SERVICE_TYPE_SENSOR: Final = "SENSOR"

# Mower states
MOWER_STATE_OK: Final = "OK"
MOWER_STATE_WARNING: Final = "WARNING"
MOWER_STATE_ERROR: Final = "ERROR"
MOWER_STATE_UNAVAILABLE: Final = "UNAVAILABLE"

# Mower activities
MOWER_ACTIVITY_PAUSED: Final = "PAUSED"
MOWER_ACTIVITY_PAUSED_IN_CS: Final = "PAUSED_IN_CS"
MOWER_ACTIVITY_CUTTING: Final = "OK_CUTTING"
MOWER_ACTIVITY_CUTTING_TIMER_OVERRIDDEN: Final = "OK_CUTTING_TIMER_OVERRIDDEN"
MOWER_ACTIVITY_SEARCHING: Final = "OK_SEARCHING"
MOWER_ACTIVITY_LEAVING: Final = "OK_LEAVING"
MOWER_ACTIVITY_CHARGING: Final = "OK_CHARGING"
MOWER_ACTIVITY_PARKED: Final = "PARKED_TIMER"
MOWER_ACTIVITY_PARKED_TIMER: Final = "PARKED_TIMER"
MOWER_ACTIVITY_PARKED_PARK_SELECTED: Final = "PARKED_PARK_SELECTED"
MOWER_ACTIVITY_PARKED_AUTOTIMER: Final = "PARKED_AUTOTIMER"
MOWER_ACTIVITY_PARKED_FROST: Final = "PARKED_FROST"
MOWER_ACTIVITY_STOPPED_IN_GARDEN: Final = "STOPPED_IN_GARDEN"
MOWER_ACTIVITY_INITIATE_NEXT_ACTION: Final = "INITIATE_NEXT_ACTION"
MOWER_ACTIVITY_SEARCHING_FOR_SATELLITES: Final = "SEARCHING_FOR_SATELLITES"
MOWER_ACTIVITY_NONE: Final = "NONE"

# Mower activity mapping to Home Assistant
MOWER_ACTIVITY_MAP: Final = {
    MOWER_ACTIVITY_PAUSED: LawnMowerActivity.PAUSED,
    MOWER_ACTIVITY_PAUSED_IN_CS: LawnMowerActivity.PAUSED,
    MOWER_ACTIVITY_CUTTING: LawnMowerActivity.MOWING,
    MOWER_ACTIVITY_CUTTING_TIMER_OVERRIDDEN: LawnMowerActivity.MOWING,
    MOWER_ACTIVITY_SEARCHING: LawnMowerActivity.MOWING,
    MOWER_ACTIVITY_LEAVING: LawnMowerActivity.MOWING,
    MOWER_ACTIVITY_CHARGING: LawnMowerActivity.DOCKED,
    MOWER_ACTIVITY_PARKED: LawnMowerActivity.DOCKED,
    MOWER_ACTIVITY_PARKED_TIMER: LawnMowerActivity.DOCKED,
    MOWER_ACTIVITY_PARKED_PARK_SELECTED: LawnMowerActivity.DOCKED,
    MOWER_ACTIVITY_PARKED_AUTOTIMER: LawnMowerActivity.DOCKED,
    MOWER_ACTIVITY_PARKED_FROST: LawnMowerActivity.DOCKED,
    MOWER_ACTIVITY_STOPPED_IN_GARDEN: LawnMowerActivity.DOCKED,
    MOWER_ACTIVITY_INITIATE_NEXT_ACTION: LawnMowerActivity.MOWING,
    MOWER_ACTIVITY_SEARCHING_FOR_SATELLITES: LawnMowerActivity.DOCKED,
    MOWER_ACTIVITY_NONE: LawnMowerActivity.ERROR,
}

# WebSocket configuration
WEBSOCKET_RECONNECT_DELAY: Final = 5  # seconds
WEBSOCKET_MAX_RECONNECT_ATTEMPTS: Final = 10

# Attribute names
ATTR_BATTERY_STATE: Final = "battery_state"
ATTR_RF_LINK_LEVEL: Final = "rf_link_level"
ATTR_RF_LINK_STATE: Final = "rf_link_state" 